name: Migacore
favicon: null
layout_spectrum: 0.11029114876873791
typography_spectrum: 0.9376517054624856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.30946514569222927
  lightness: 0.862156939227134
  saturation: 0.3960367070976645
  rhythmicContrast: 0.887615131912753
purpose: []
